import type { Metadata } from "next";
import "./globals.css";
import MainContainer from "./components/layout/MainContainer";
import AuthProvider from "./context/AuthContext";

export const metadata: Metadata = {
  title: "CODE CHALLENGE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <MainContainer >
          <AuthProvider>
            {children}  

          </AuthProvider>
        </MainContainer>
      </body>
    </html>
  );
}
